version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    ignore:
      - dependency-name: "connectedhomeip"
    schedule:
      interval: "daily"
    target-branch: main
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
